version: '3'

volumes:
  mongo-account-db:
services:
  mongo-account:
    image: mongo
    volumes:
      - mongo-account-db:/data/db
    ports:
      - 27011:27017

  rabbitmq:
    image: rabbitmq:3.6-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: ofamily
    ports:
      - 15672:15672
      - 5672:5672